language: python
env:
  - DJANGO_VERSION=1.4.22
  - DJANGO_VERSION=1.5.12
  - DJANGO_VERSION=1.6.11
  - DJANGO_VERSION=1.7.11
  - DJANGO_VERSION=1.8.8
  - DJANGO_VERSION=1.9.1
python:
  - 3.5
matrix:
  include:
    - python=2.7
      env=DJANGO_VERSION=1.9.1
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install coveralls
script:
  - coverage run -m unittest discover -s tests -p *_test.py
after_success:
  - coveralls