language: python
env:
  - DJANGO_VERSION=1.4.22
  - DJANGO_VERSION=1.5.12
  - DJANGO_VERSION=1.6.11
  - DJANGO_VERSION=1.7.11
  - DJANGO_VERSION=1.8.8
  - DJANGO_VERSION=1.9.1
python:
  - 2.7
  - 3.5
matrix:
  exclude:
    - python: 3.5
      env: DJANGO_VERSION=1.4.22
    - python: 3.5
      env: DJANGO_VERSION=1.5.12
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install coveralls mock
script:
  - coverage run -m unittest discover -s tests -p *_test.py
after_success:
  - coveralls