language: python

matrix:
  include:
    - python: 2.7
      env: DJANGO_VERSION=1.4.22
    - python: 2.7
      env: DJANGO_VERSION=1.5.12
    - python: 2.7
      env: DJANGO_VERSION=1.6.11
    - python: 2.7
      env: DJANGO_VERSION=1.7.11
    - python: 2.7
      env: DJANGO_VERSION=1.8.8
    - python: 2.7
      env: DJANGO_VERSION=1.9.1
    - python: 3.5
      env: DJANGO_VERSION=1.9.1

install:
  - pip install coveralls
  - pip install -q Django==$DJANGO_VERSION
  - pip install --upgrade mock

script:
  - coverage run -m unittest discover -s tests -p *_test.py

after_success:
  - coveralls