language: python

env:
  global:
    - DATABASE_NAME=travis
    - DATABASE_USER=travis
    - DATABASE_PASSWORD=""
    - DATABASE_HOST=127.0.0.1
    - DATABASE_PORT=5432
  matrix:
    - DJANGO_VERSION=1.4.22
    - DJANGO_VERSION=1.5.12
    - DJANGO_VERSION=1.6.11
    - DJANGO_VERSION=1.7.11
    - DJANGO_VERSION=1.8.13
    - DJANGO_VERSION=1.9.7

python:
  - 2.7

matrix:
  include:
    - python: 3.5
      env: DJANGO_VERSION=1.9.7

addons:
  postgresql: 9.4

services:
  - postgresql

install:
  - pip install coveralls psycopg2 pyyaml south
  - pip install -q Django==$DJANGO_VERSION
  - pip install --upgrade mock

script:
  - python manage.py migrate
  - coverage run manage.py test testapp

after_success:
  - coveralls
