language: python

env:
  global:
    - DATABASE_NAME=travis
    - DATABASE_USER=travis
    - DATABASE_PASSWORD=""
    - DATABASE_HOST=127.0.0.1
    - DATABASE_PORT=5432
  matrix:
    - DJANGO_VERSION=1.8.18
    - DJANGO_VERSION=1.9.13
    - DJANGO_VERSION=1.10.8
    - DJANGO_VERSION=1.11.9

python: 2.7

matrix:
  include:
    - python: 3.4
      env: DJANGO_VERSION=1.11.9
    - python: 3.5
      env: DJANGO_VERSION=1.11.9
    - python: 3.6
      env: DJANGO_VERSION=1.11.9

addons:
  postgresql: 9.4

services: postgresql

install:
  - pip install coveralls psycopg2 pyyaml psutil
  - pip install -q Django==$DJANGO_VERSION
  - pip install --upgrade mock

before_script:
  - python manage.py migrate

script: coverage run manage.py test tests

after_success: coveralls
