language: python

env:
  global:
    - DATABASE_NAME=travis
    - DATABASE_USER=travis
    - DATABASE_PASSWORD=""
    - DATABASE_HOST=127.0.0.1
    - DATABASE_PORT=5432
  matrix:
    - DJANGO_VERSION=1.4.22
    - DJANGO_VERSION=1.5.12
    - DJANGO_VERSION=1.6.11
    - DJANGO_VERSION=1.7.11
    - DJANGO_VERSION=1.8.19
    - DJANGO_VERSION=1.9.13
    - DJANGO_VERSION=1.10.7
    - DJANGO_VERSION=1.11

python: 2.7

matrix:
  include:
    - python: 3.5
      env: DJANGO_VERSION=1.11

addons:
  postgresql: 9.4

services: postgresql

install:
  - pip install coveralls psycopg2 pyyaml south
  - pip install -q Django==$DJANGO_VERSION
  - pip install --upgrade mock

before_script:
  - ./travis_syncdb.sh
  - python manage.py migrate

script: coverage run manage.py test testapp

after_success: coveralls
