# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-22 04:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timestampabletest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='timestampabletest',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='tests_timestampabletest_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='timestampabletest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Removal date'),
        ),
        migrations.AlterField(
            model_name='timestampabletest',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests_timestampabletest_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by'),
        ),
        migrations.AlterField(
            model_name='timestampabletest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date of last update'),
        ),
        migrations.AlterField(
            model_name='timestampabletest',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests_timestampabletest_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
    ]
